# Site settings
title: Nick Cronin
email: nick@cronin.id.au
description: "JVM & useful programming discoveries"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.cronin.id.au" # the base hostname & protocol for your site
twitter_username: CroninNick
github_username:  quintok

# Build settings
markdown: kramdown
